// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Books []*Book `json:"books"`
}

type Book struct {
	ID     string  `json:"id"`
	Title  string  `json:"title"`
	Type   *string `json:"type,omitempty"`
	Author *Author `json:"author"`
}

type NewAuthor struct {
	Name string `json:"name"`
}

type NewBook struct {
	Title  string `json:"title"`
	Author string `json:"author"`
}
